module.exports = {
  'api/docs': {
    match: /^api\/docs(\/)?$/,
    methods: 'GET',
    notEmptyParamsName: [],
    needToVerifyUser: true,
  },
  'api/create/doc': {
    match: /^api\/create\/doc(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['space_id', 'title', 'scene'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/doc/detail': {
    match: /^api\/doc\/detail(\/)?$/,
    methods: 'GET',
    notEmptyParamsName: ['doc_id'],
    needToVerifyUser: true,
  },
  'api/doc/update': {
    match: /^api\/doc\/update(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['doc_id'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/doc/delete': {
    match: /^api\/doc\/delete(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['doc_id', 'space_id'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/add/recent': {
    match: /^api\/add\/recent(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['type'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/delete/recent': {
    match: /^api\/delete\/recent(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['id'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/recents': {
    match: /^api\/recents(\/)?$/,
    methods: 'GET',
    notEmptyParamsName: [],
    needToVerifyUser: true,
  },
  'api/space/docs': {
    match: /^api\/space\/docs(\/)?$/,
    methods: 'GET',
    notEmptyParamsName: ['space_id'],
    needToVerifyUser: true,
  },
  'api/create/space': {
    match: /^api\/create\/space(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['public', 'scene', 'name', 'description'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/spaces': {
    match: /^api\/spaces(\/)?$/,
    methods: 'GET',
    notEmptyParamsName: [],
    needToVerifyUser: true,
  },
  'api/spaces/update': {
    match: /^api\/spaces\/update(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['space_id'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/spaces/delete': {
    match: /^api\/spaces\/delete(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['space_id'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/create/template': {
    match: /^api\/create\/template(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['html', 'url'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/delete/template': {
    match: /^api\/delete\/template(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['templateId'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/templates': {
    match: /^api\/templates(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: [],
    needToVerifyUser: true,
  },
  'api/create/shortcut': {
    match: /^api\/create\/shortcut(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['title', 'url', 'type'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/delete/shortcut': {
    match: /^api\/delete\/shortcut(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['shortcutId'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/shortcut/order': {
    match: /^api\/shortcut\/order(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['sourceShortcutId', 'sourceOrderNum', 'destinationOrderNum'],
    access: 'SUPER_ADMIN',
    needToVerifyUser: true,
  },
  'api/shortcut': {
    match: /^api\/shortcut(\/)?$/,
    methods: 'GET',
    notEmptyParamsName: [],
    needToVerifyUser: true,
  },
  'api/search': {
    match: /^api\/search(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['q'],
    needToVerifyUser: true,
  },
  'api/ip': {
    match: /^api\/ip(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['ip'],
    needToVerifyUser: true,
  },
  'api/ips': {
    match: /^api\/ips(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: [],
    needToVerifyUser: true,
  },
  'api/currentIp': {
    match: /^api\/currentIp(\/)?$/,
    methods: 'GET',
    notEmptyParamsName: [],
    needToVerifyUser: true,
  },
  'api/deleteIp': {
    match: /^api\/deleteIp(\/)?$/,
    methods: 'POST',
    notEmptyParamsName: ['ip'],
    needToVerifyUser: true,
  },
};